added action-junit-report github action

diff --git a/.github/workflows/java_gradle.yaml b/.github/workflows/java_gradle.yaml
--- a/.github/workflows/java_gradle.yaml
+++ b/.github/workflows/java_gradle.yaml
@@ -45,3 +45,8 @@ jobs:
         run: chmod +x gradlew
       - name: Build (and test) with Gradle
         run: ./gradlew build
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+            report_paths: '**/build/test-results/test/TEST-*.xml'
